version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logged in successfully.
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t stock-prediction-app .
      - docker tag stock-prediction-app:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stock-prediction-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stock-prediction-app:latest
artifacts:
  files: []
